### ISSUE TITLE
sed: can't read /etc/ldap-account-manager/config.cfg: No such file or directory

### ISSUE THREAD

**Issue by daletman** [LDAPAccountManager/docker#5]
When I mount volumes to store config files outside I get the following error on startup:

sed: can't read /etc/ldap-account-manager/config.cfg: No such file or directory

I'm on macOS.
I'm using the following docker-compose file:

```yaml
services:
  lam:
    container_name: lam
    image: ghcr.io/ldapaccountmanager/lam:stable
    ports:
      - 8090:80
    env_file:
      - .env
    volumes:
      - ./data/lam/etc/:/etc/ldap-account-manager
      - ./data/lam/lib/:/var/lib/ldap-account-manager
```
