### ISSUE TITLE
Password problem during setup

### ISSUE THREAD

**Issue by 3L-OSO** [LDAPAccountManager/docker#8]
Hello,

I'm trying to set up a profile and when I have to enter the master password, I enter "lam" and I get this error message: "Master password is wrong!"
I tried to pass a password via the environment variable LAM_PASSWORD, but I still have the same problem.
I deleted the volumes and containers and repeated the procedure, but nothing helped.
I tried with and without the LAM_SKIP_PRECONFIGURE variable and I still have the same result.

Here is my docker compose service: 
```yml
lam:
    image: ldapaccountmanager/lam:stable
    container_name: lam
    hostname: lam.mydomain.com
    environment:
      LAM_SKIP_PRECONFIGURE: "true"
      VIRTUAL_HOST: "lam.mydomain.com"
      VIRTUAL_PORT: "80"
    volumes:
      - /datas/volumes/ldap/lam/config:/var/lib/ldap-account-manager/config
      - /datas/volumes/ldap/lam/sess:/var/lib/ldap-account-manager/sess
    networks:
      - ldap
      - web
    # restart: always
    depends_on:
      - openldap
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.lam.rule=Host(`lam.mydomain.com`)"
      - "traefik.http.routers.lam.entrypoints=websecure"
      - "traefik.http.services.lam.loadbalancer.server.port=80"
      - "traefik.http.services.lam.loadbalancer.server.scheme=http"
      - "traefik.http.routers.lam.tls.certresolver=myresolver"
```

NB: I got the config folder from the tar.bz2 of lam 9.0 to place it in the config volume, but the latest docker tag seems to be 9.0 too.

I think I respected the doc, however, I must have missed something.

Thanks,
